# Usage:
# docker build -t zombie-backend .
# docker run -d -p 3300:3300 -p 4430:443 --name zombie-backend --restart always zombie-backend
FROM node	
COPY zombie-backend /app	
WORKDIR /app
RUN npm install --registry=https://registry.npm.taobao.org \ 
&& apt-get update && apt-get -y install python3-pip \
&& pip3 install -r requirements.txt
EXPOSE 3300	443
CMD npm start